apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
provisioner: fuseim.pri/ifs
parameters:
  archiveOnDelete: "false"
