apiVersion: v1
kind: Namespace
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  namespace: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: nfs-client-provisioner
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.0.13
            - name: NFS_PATH
              value: /mnt/nfsserver
      volumes:
        - name: nfs-client-root
          nfs:
            # this is node-rp4-1
            # todo: do not hardcode it
            server: 192.168.0.13
            path: /mnt/nfsserver
