version: "3.3"
services:
### dnscrypt-server
  dnscrypt-server:
    container_name: dnscrypt-server
    image: nutshells/dnscrypt-wrapper
    #command: [ "init" ]
    ports:
      - "127.0.0.1:5353:12345/tcp"
      - "127.0.0.1:5353:12345/udp"
    environment:
      - RESOLVER_IP=upstream
      - RESOLVER_PORT=12345
      #- PROVIDER_BASENAME=your_domain.com
    volumes:
      - type: bind
        source: <keys_dir>
        target: /usr/local/etc/dnscrypt-wrapper
    networks:
        - network
    depends_on:
        - upstream
    read_only: true
    restart: unless-stopped

### upstream
  upstream:
    container_name: dnscrypt-upstream
    image: nutshells/dnsmasq-fast-lookup
    command: [
      #"start",
      "--domain-needed",
      "--bogus-priv",
      #"--dnssec",
      #"--dnssec-check-unsigned",
      #"--trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5",
      #"--dnssec-debug",
      "--no-resolv",
      "--no-hosts",
      "--cache-size=10240",
      "--server=8.8.8.8",
    ]
    networks:
        - network
    read_only: true
    restart: unless-stopped

### network
networks:
    network:
