apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
  labels:
    component: "node-exporter"
    app: prometheus
spec:
  selector:
    matchLabels:
      component: "node-exporter"
      app: prometheus
  updateStrategy:
    type: RollingUpdate
    
  template:
    metadata:
      namespace: prometheus
      labels:
        component: "node-exporter"
        app: prometheus
    spec:
      serviceAccountName: prometheus-node-exporter
      containers:
        - name: prometheus-node-exporter
          image: "prom/node-exporter:v0.18.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            {}
            
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-arm-exporter
  namespace: prometheus
  labels:
    component: "arm-exporter"
    app: prometheus
spec:
  selector:
    matchLabels:
      component: "arm-exporter"
      app: prometheus
  updateStrategy:
    type: RollingUpdate
    
  template:
    metadata:
      namespace: prometheus
      labels:
        component: "arm-exporter"
        app: prometheus
    spec:
      serviceAccountName: prometheus-node-exporter
      containers:
        - name: prometheus-arm-exporter
          image: "carlosedp/arm_exporter"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 9243
              hostPort: 9243
            
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly:  true
            - name: hostname
              mountPath: /etc/hostname
              readOnly: true
            - name: timezone
              mountPath: /etc/TZ
              readOnly: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: hostname
          hostPath:
            path: /etc/hostname
        - name: timezone
          hostPath:
            path: /etc/timezone
