apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: prometheus
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    component: "server"
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
    
  resources:
    requests:
      storage: "4Gi"
