apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
  annotations:
    prometheus.io/scrape: "true"
    
  labels:
    component: "node-exporter"
    app: prometheus
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
  type: "ClusterIP"

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus
  labels:
    component: "server"
    app: prometheus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    component: "server"
    app: prometheus
  type: "ClusterIP"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic		
    nginx.ingress.kubernetes.io/auth-secret: basic-auth		
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Prometheus'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - prometheus.galaiko.rocks
    secretName: prometheus-tls
  rules:
  - host: prometheus.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-server
          servicePort: http
