#!/bin/bash

set -x

/usr/local/dnscrypt-proxy/dnscrypt-proxy &

create_ap \
    -m bridge \
    --country=SE \
    --dhcp-dns 1.1.1.1 \
    $AP_WIFI_IFACE \
    $AP_INTERNET_IFACE \
    $AP_SSID \
    $AP_PASSPHRASE
