apiVersion: v1
kind: Namespace
metadata:
  name: pihole

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      namespace: pihole
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:4.3.2-1_armhf
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns
          protocol: UDP
        resources:
          requests:
            cpu: 300m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        volumeMounts:
          - mountPath: /etc/pihole
            name: pihole
            readOnly: false
          - mountPath: /etc/dnsmasq.d
            name: dnsmasq
            readOnly: false
        env:
          - name: TZ
            value: Europe/Stockholm
          - name: VIRTUAL_HOST
            value: dns.galaiko.rocks
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                name: dns-password
                key: DNS_PASSWORD
      volumes:
      - name: pihole
        persistentVolumeClaim:
          claimName: pihole
      - name: dnsmasq
        persistentVolumeClaim:
          claimName: dnsmasq
