apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ui
spec:
  rules:
  - host: dns.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: pihole
          servicePort: http
