apiVersion: v1
kind: Service
metadata:
  name: pihole-ui
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: dns
      port: 53
      targetPort: dns
      protocol: UDP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ui
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dns.galaiko.rocks
    secretName: pihole-tls
  rules:
  - host: dns.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: pihole-ui
          servicePort: http
