kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole
  namespace: pihole
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16M

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dnsmasq
  namespace: pihole
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8M
