apiVersion: v1
kind: Namespace
metadata:
  name: miniflux

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      namespace: miniflux
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: miniflux/miniflux:arm32v6-2.0.13
        ports:
        - containerPort: 8443
          name: https
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        env:
          - name: HTTPS
            value: "true"
          - name: CERT_FILE
            value: "/tls/tls.crt"
          - name: KEY_FILE
            value: "/tls/tls.key"
          - name: PORT
            value: "8443"
          - name: BASE_URL
            value: "https://rss.galaiko.rocks"
          - name: RUN_MIGRATIONS
            value: "1"
          - name: CREATE_ADMIN
            value: "1"
          - name: ADMIN_USERNAME
            value: "ngalaiko"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rss-password
                key: RSS_PASSWORD
          - name: POLLING_FREQUENCY
            value: "5"
          - name: WORKER_POOL_SIZE
            value: "50"
          - name: BATCH_SIZE
            value: "50"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: miniflux-database-url
                key: MINIFLUX_DATABASE_URL
        volumeMounts:
        - name: tls-certificate
          mountPath: /tls

      volumes:
      - name: tls-certificate
        secret:
          secretName: tls-certificate
