apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: ngalayko/miniflux:arm32v7
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        env:
          - name: PORT
            value: "8080"
          - name: BASE_URL
            value: "https://rss.galaiko.rocks"
          - name: RUN_MIGRATIONS
            value: "1"
          - name: CREATE_ADMIN
            value: "1"
          - name: ADMIN_USERNAME
            value: "ngalaiko"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rss-password
                key: RSS_PASSWORD
          - name: POLLING_FREQUENCY
            value: "5"
          - name: WORKER_POOL_SIZE
            value: "50"
          - name: BATCH_SIZE
            value: "50"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: miniflux-database-url
                key: MINIFLUX_DATABASE_URL
