apiVersion: v1
kind: Namespace
metadata:
  name: fathom

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fathom
  namespace: fathom
  labels:
    app: fathom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fathom
  template:
    metadata:
      namespace: fathom
      labels:
        app: fathom
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: fathom
        image: ngalayko/fathom
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        env:
          - name: FATHOM_SERVER_ADDR
            value: ":8080"
          - name: FATHOM_DEBUG
            value: "true"
          - name: FATHOM_DATABASE_DRIVER
            value: postgres
          - name: FATHOM_DATABASE_NAME
            value: fathom
          - name: FATHOM_DATABASE_USER
            value: postgres
          - name: FATHOM_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pass
                key: POSTGRES_PASS
          - name: FATHOM_DATABASE_HOST
            value: postgres.postgres
          - name: FATHOM_DATABASE_SSLMODE
            value: disable
          - name: FATHOM_SECRET
            valueFrom:
              secretKeyRef:
                name: fathom-secret
                key: FATHOM_SECRET
