apiVersion: v1
kind: Service
metadata:
  name: fathom
  labels:
    app: fathom
spec:
  selector:
    app: fathom
  ports:
    - name: http
      port: 8080
      targetPort: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fathom
  labels:
    app: fathom
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
spec:
spec:
  tls:
  - hosts:
    - analytics.galaiko.rocks
    secretName: fathom-tls
  rules:
  - host: analytics.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: fathom
          servicePort: http
