version: "2"

services:
  analytics:
    restart: always
    build: ./analytics
    container_name: analytics
    environment:
      - VIRTUAL_HOST=analytics.${HOST}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=analytics.${HOST}
      - LETSENCRYPT_EMAIL=ngalayko@gmail.com
    ports:
      - "80"
    links:
      - "analytics-data:db"

  analytics-data:
     restart: always
     image: mysql:8.0.12
     container_name: analytics-data
     environment:
       - MYSQL_ROOT_PASSWORD=pasword
       - MYSQL_DATABASE=matomo
     volumes:
       - "/data/matomo/data/:/var/lib/mysql/"
