version: '3'

services:
    vpn:
        build: ./vpn
        container_name: vpn
        privileged: true
        environment:
            - VPN_IPSEC_PSK=${VPN_IPSEC_PSK}
            - VPN_USER=${VPN_USER}
            - VPN_PASSWORD=${VPN_PASSWORD}
        ports:
            - "500:500/udp"
            - "4500:4500/udp"
        volumes:
            - "/lib/modules:/lib/modules"
        restart: unless-stopped
