version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /data/proxy/certs:/etc/nginx/certs
        restart: unless-stopped
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    nginx-gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - /data/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /etc/nginx/certs
            - /data/proxy/certs:/etc/nginx/certs
        restart: unless-stopped

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-nginx-proxy-companion
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /data/proxy/certs:/etc/nginx/certs
        restart: unless-stopped
