version: '2'
services:
    goaccess-front:
        restart: always
        container_name: goaccess-front
        image: nginx:1.14.0-alpine
        expose: 
            - "80"
        ports: 
            - "80"
        volumes: 
            - "./goaccess/html:/usr/share/nginx/html:ro"
        environment:
            - VIRTUAL_HOST=goaccess.${HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=goaccess.${HOST}
            - LETSENCRYPT_EMAIL=ngalayko@gmail.com

    goaccess:
        restart: always
        container_name: goaccess
        image: allinurl/goaccess
        expose:
            - "7890"
        ports: 
            - "7890"
        volumes: 
            - "./goaccess/data:/srv/data"
            - "./goaccess/logs:/srv/logs"
            - "./goaccess/html:/srv/report"
            - "/data/proxy/certs/ws.galayko.rocks.key:/srv/certs/ws.galayko.rocks.key:ro"
            - "/data/proxy/certs/ws.galayko.rocks.crt:/srv/certs/ws.galayko.rocks.crt:ro"
        environment:
            - VIRTUAL_HOST=ws.${HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=7890
            - LETSENCRYPT_HOST=ws.${HOST}
            - LETSENCRYPT_EMAIL=ngalayko@gmail.com
