version: '3'

services:
    analytics-data:
        image: mysql:8.0.12
        container_name: analytics-data
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - /data/matomo/data/:/var/lib/mysql/
            - ./analytics/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        restart_policy: 
            condition: any
            delay: 3s
            max_attempts: 3
            window: 120s

    analytics-backend:
        image: matomo:3.6.0-fpm-alpine
        container_name: analytics-backend
        links:
            - analytics-data
        volumes:
            - /data/matomo/config:/var/www/html/config
        restart_policy: 
            condition: any
            delay: 3s
            max_attempts: 3
            window: 120s

    analytics-frontend:
        image: nginx:1.13.3-alpine
        container_name: analytics-frontend
        environment:
            - VIRTUAL_HOST=analytics.${HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=analytics.${HOST}
            - LETSENCRYPT_EMAIL=ngalayko@gmail.com
        volumes:
            - ./analytics/nginx.conf:/etc/nginx/nginx.conf:ro
        volumes_from:
            - analytics-backend
        ports:
            - 80
        links:
            - analytics-backend:app
        restart_policy: 
            condition: any
            delay: 3s
            max_attempts: 3
            window: 120s
