version: '3'

services:
    analytics-data:
        image: mysql:8.0.12
        container_name: analytics-data
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - /data/matomo/data/:/var/lib/mysql/
            - ./analytics/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        restart: unless-stopped

    analytics-backend:
        image: matomo:3.6.0-fpm-alpine
        container_name: analytics-backend
        links:
            - analytics-data
        volumes:
            - /data/matomo:/var/www/html
        restart: unless-stopped

    analytics-frontend:
        image: ngalayko/nginx
        container_name: analytics-frontend
        environment:
            - VIRTUAL_HOST=analytics.${HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=analytics.${HOST}
            - LETSENCRYPT_EMAIL=ngalayko@gmail.com
        volumes:
            - /data/matomo:/var/www/html
            - ./analytics/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80
        links:
            - analytics-backend:app
        restart: unless-stopped
