version: '2'
services:
    fluentd:
        restart: always
        container_name: fluentd
        build:
            context: ./logs/fluentd
            dockerfile: Dockerfile
        volumes:
            - "./logs/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf"
        links:
            - "elasticsearch"
        ports:
            - "24224:24224"
            - "24224:24224/udp"

    elasticsearch:
        restart: always
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        expose:
            - 9200
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512gm -Xmx512gm"

    kibana:
        restart: always
        container_name: kibana
        image: kibana:5.6.12
        links:
            - "elasticsearch"
        ports:
            - "5601:5601"
        environment:
        - VIRTUAL_HOST=logs.${HOST}
        - VIRTUAL_NETWORK=nginx-proxy
        - VIRTUAL_PORT=5601
        - LETSENCRYPT_HOST=${HOST}
        - LETSENCRYPT_EMAIL=ngalayko@gmail.com
