version: "2"

services:
  analytics-data:
    restart: always
    image: mysql:8.0.12
    container_name: analytics-data
    environment:
      - MYSQL_ROOT_PASSWORD=pasword
      - MYSQL_DATABASE=matomo
    volumes:
      - "/data/matomo/data/:/var/lib/mysql/"

  analytics-backend:
    restart: always
    image: matomo:3.5.1-fpm-alpine
    container_name: analytics-backend
    links:
      - "analytics-data:db"
    volumes:
      - "/data/matomo/config:/var/www/html/config"

  analytics-frontend:
   restart: always
   image: nginx:1.13.3-alpine
   container_name: analytics-frontend
   environment:
     - VIRTUAL_HOST=analytics.${HOST}
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=analytics.${HOST}
     - LETSENCRYPT_EMAIL=ngalayko@gmail.com
   volumes:
     - "./analytics/nginx.conf:/etc/nginx/nginx.conf:ro"
   volumes_from:
     - analytics-backend
   ports:
     - "80"
   links:
     - "analytics-backend:app"
