version: '3'

services:
    autoheal:
        build: ./autoheal
        container_name: autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - AUTOHEAL_INTERVAL = 10
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: 
            condition: any
            delay: 3s
            max_attempts: 3
            window: 120s
