FROM fg2it/grafana-armhf:v5.1.4

COPY datasources /etc/grafana/provisioning/datasources/
COPY dashboards.yml /etc/grafana/provisioning/dashboards/
COPY dashboards /etc/grafana/dashboards/

ENV GF_PATHS_PROVISIONING=/etc/grafana/provisioning/

USER root
