libstorage:
  service: s3fs
s3fs:
  accessKey: access-key
  secretKey: secret-key
  endpoint: http://localhost:9000  
  region: us-east-1
  disablePathStyle: false 
  options:
  - url=http://localhost:9000
  - use_path_request_style
  - nonempty
