version: '3.4'

volumes:
    matomo_data:
    matomo_html:
        driver: ngalayko/rexray-s3fs
        name: matomo.html

networks:
    analytics:
        driver: overlay

services:
    analytics-data:
        image: ngalayko/mysql:arm32v7
        networks:
            - analytics
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=matomo
            - MYSQL_USER=matomo
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - matomo_data:/var/lib/mysql
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.labels.analytics==true"
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M
            placement:
                constraints:
                    - "node.labels.analytics==true"

    analytics-backend:
        image: ngalayko/matomo:arm32v7
        networks:
            - analytics
        depends_on:
            - analytics-data
        volumes:
            - matomo_html:/var/www/html
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    analytics-frontend:
        image: ngalayko/nginx:arm32v7
        networks:
            - traefik
            - analytics
        volumes:
            - matomo_html:/var/www/html
            - ../../containers/analytics/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - analytics-backend
        deploy:
            replicas: 1
            labels:
                - "traefik.port=80"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:analytics.${HOST}"
