version: '3.4'

networks:
    hostnet:
        external: true

services:
    wifi-ap:
        image: ngalayko/wifi-ap:arm32v7
        networks:
            hostnet: {}
        volumes:
            - "/dev/urandom:/dev/random"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
