version: '3.4'

networks:
    fathom:
        driver: overlay

services:
    fathom:
        image: ngalayko/fathom:arm32v7
        networks:
            - traefik
            - fathom
        environment:
            - FATHOM_DEBUG=false
            - FATHOM_DATABASE_DRIVER=postgres
            - FATHOM_DATABASE_URL=postgres://postgres:${POSTGRES_PASS}@postgres/fathom?sslmode=disable
            - FATHOM_SECRET=${FATHOM_SECRET}
        deploy:
            replicas: 1
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:analytics.${HOST}"
