version: '3.4'

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - traefik
        environment:
            - TZ=Europe/Stockholm
        ports:
            - 8123:8123
        labels:
            - "traefik.port=8123"
            - "traefik.docker.network=server_traefik"
            - "traefik.frontend.rule=Host:home.${HOST}"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.labels.home==true"
