version: '3.4'

networks:
    outside:
        external:
            name: "host"

services:
    wifi-ap:
        image: ngalayko/wifi-ap:arm32v7
        networks:
            - outside
        volumes:
            - "/dev/urandom:/dev/random"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
