version: '3.4'

volumes:
    home_assistant_config:

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - traefik
        environment:
            - TZ=Europe/Stockholm
        volumes:
            - home_assistant_config:/config
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=8123"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:home.${HOST}"
            placement:
                constraints:
                    - "node.labels.home==true"
