version: '3.4'

services:
    wifi-ap:
        image: ngalayko/wifi-ap:arm32v7
        privileged: true
        volumes:
            - "/dev/urandom:/dev/random"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
