version: '3.4'

volumes:
  consul-data:

services:
    consul:
        image: arm32v6/consul:1.3.0
        command: agent -server -bootstrap-expect=1 -ui
        ports:
            - 8500:8500
        volumes:
            - consul-data:/consul/data
        environment:
            - CONSUL_LOCAL_CONFIG={"server":true}
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
