version: '3.4'

networks:
    home_assistant_host:
        external:
             name: "host"

volumes:
    home_assistant_config:
        driver: "ngalayko/sshfs:arm32v7"
        driver_opts:
            allow_other: ""
            sshcmd: "pirate@node-white:/home/pirate/data/home-assistant"

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - home_assistant_host
        environment:
            - LONGITUDE=${LONGITUDE}
            - LATITUDE=${LATITUDE}
            - HOST=home.{HOST}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DARKSKY_TOKEN=${DARKSKY_TOKEN}
            - IKEA_TRADFRI_IP=${IKEA_TRADFRI_IP}
        volumes:
            - home_assistant_config:/config/config
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.labels.home==true"
