version: '3.4'

volumes:
    dnscrypt:

services:
    pihole:
        image: ngalayko/pihole:arm32v7
        environment:
            - ServerIP=${SERVER_IP}
            - VIRTUAL_HOST=dns.${HOST}
            - TZ=Europe/Stockholm
            - WEBPASSWORD=${DNS_PASSWORD}
        volumes:
            - /data/dns/pihole/:/etc/pihole/
            - /data/dns/dnsmasq.d/:/etc/dnsmasq.d/
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.labels.dns==true"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.docker.network=server_traefik"
                - "traefik.web.port=80"
                - "traefik.web.frontend.rule=Host:dns.${HOST}"

    dnscrypt:
        image: ngalayko/dnscrypt:arm32v7
        command: init
        environment: 
            - PROVIDER_BASENAME=connect.dns.${HOST}
        networks:
            - traefik
        volumes:
            - dnscrypt:/usr/local/etc/dnscrypt-wrapper
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.hostname == node-black]
            labels:
                - "traefik.docker.network=server_traefik"
                - "traefik.dns.port=443"
                - "traefik.dns.frontend.rule=Host:2.dnscrypt-cert.connect.dns.${HOST}"
