version: '3.4'

networks:
    outside:
        external:
            name: "host"

services:
    wifi-ap:
        image: forcedinductionz/docker-ap:latest-armhf
        networks:
            - outside
        environment:
            - INTERFACE=wlan0
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
