version: '3.4'

networks:
    traefik:
        driver: overlay

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        ports:
            - 80:80
            - 443:443
            - 8090:8080
        environment:
            - DO_AUTH_TOKEN=${DIGITAL_OCEAN_AUTH_TOKEN}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
            - /data/stats:/var
        networks:
            - traefik
            - monitoring
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure

    dyn-dns:
        image: ngalayko/dyn-dns:arm32v7
        command: --apiToken=${DYN_DNS_TOKEN} --domain="${HOST}" --interval=10s
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    goaccess:
        image: ngalayko/goaccess:arm32v7
        volumes:
            - /data/stats:/srv
            - /data/stats/log:/srv/log
            - /data/stats/certs:/srv/data/certs
        networks:
            - traefik
        ports:
            - 8443:443
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=443"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:ws.stats.${HOST}"

    goaccess-front:
        image: ngalayko/nginx:arm32v7
        volumes:
            - /data/stats/report:/usr/share/nginx/html:ro
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=80"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:stats.${HOST}"
