version: '3.4'

volumes:
    home_assistant_config:

networks:
    home_assistant:

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - traefik
            - home_assistant
        environment:
            - LONGITUDE=${LONGITUDE}
            - LATITUDE=${LATITUDE}
            - HOST=home.{HOST}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DARKSKY_TOKEN=${DARKSKY_TOKEN}
            - POSTGRES_PASS=${POSTGRES_PASS}
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=8123"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:home.${HOST}"
