version: '3.4'

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - traefik
        environment:
            - TZ=Europe/Stockholm
        labels:
            - "traefik.port=8123"
            - "traefik.docker.network=server_traefik"
            - "traefik.frontend.rule=Host:review-slots.${HOST}"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
