version: '3.4'

networks:
    p2p:
        driver: overlay

services:
    p2p-dispatcher:
        image: ngalayko/dispatcher
        command: --port=20000 --jwt_secret=secret --network_name=zk65o0bkwie5 --image_name=docker.io/ngalayko/peer
        networks:
            - traefik
            - p2p
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            restart_policy:
                condition: any
            labels:
                - "traefik.docker.network=server_traefik"
                - "traefik.web.port=20000"
                - "traefik.web.frontend.rule=Host:messenger.${HOST}"
