version: '3.3'

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        command: --api.dashboard \
            --docker \
            --docker.swarmmode \
            --docker.watch \
            --docker.domain=docker.swarm
              #- --entryPoints='Name:https Address::443 SSL Compress:true'
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure

networks:
    traefik:
        driver: overlay
