version: '3.4'

networks:
    outside:
        external:
            name: "host"

services:
    wifi-ap-supervisor:
        image: arm32v6/docker
        command: docker run -e AP_SSID=${WIFI_SSID} -e AP_PASSPHRASE=${ENV_WIFI_PASSWORD} --privileged --net host ngalayko/docker-ap-arm32v7
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
