version: '3.4'

networks:
    traefik:
        driver: overlay

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        command:
            - "--api"
            - "--api.dashboard=true"
            - "--entrypoints=Name:http Address::80"
            - "--entrypoints=Name:https Address::443 TLS Compress:true TLS.MinVersion:VersionTLS12 TLS.CipherSuites:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            - "--defaultentrypoints=http,https"
            - "--acme"
            - "--acme.storage=traefik/acme/account"
            - "--acme.dnsChallenge.provider=cloudflare"
            - "--acme.dnsChallenge.delayBeforeCheck=0"
            - "--acme.entryPoint=https"
            - "--acme.OnHostRule=true"
            - "--acme.acmeLogging=true"
            - "--acme.email=${EMAIL}"
            - "--acme.domains=*.p2p.${HOST}"
            - "--docker"
            - "--docker.domain=${HOST}"
            - "--docker.watch=true"
            - "--docker.swarmmode=true"
            - "--metrics"
            - "--metrics.prometheus"
            - "--metrics.prometheus.entrypoint=traefik"
            - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
            - "--accessLog"
            - "--accessLog.filePath=/var/log/traefik/access.log"
            - "--consul"
            - "--consul.watch=true"
            - "--consul.endpoint=consul:8500"
            - "--consul.prefix=traefik"
            - "--consulCatalog.endpoint=consul:8500"
            - "--consulCatalog.domain=p2p.${HOST}"
            - "--consulCatalog.frontendRule=Host:{{.ServiceName}}.{{.Domain}}"
        depends_on:
            - consul
        ports:
            - 80:80
            - 443:443
            - 8090:8080
        environment:
            - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
            - CF_API_KEY=${CLOUDFLARE_TOKEN}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik
            - p2p
        deploy:
            mode: global
            placement:
                constraints: 
                    - "node.role==manager" 
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s

    dyn-dns:
        image: ngalayko/dyn-dns:arm32v7
        command: --dnsProvider=cloudflare --apiToken=${CLOUDFLARE_TOKEN} --email=${CLOUDFLARE_EMAIL} --zoneIdentifier=${CLOUDFLARE_ZONE} --record=selfhosted --domain="${HOST}" --interval=10m
        deploy:
            replicas: 1
            restart_policy:
                condition: any
