version: '3.4'

volumes:
    dnscrypt:

services:
    pihole:
        image: ngalayko/pihole:arm32v7
        environment:
            - ServerIP=${SERVER_IP}
            - VIRTUAL_HOST=dns.${HOST}
            - TZ=Europe/Stockholm
            - WEBPASSWORD=${DNS_PASSWORD}
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 3000:3000
        volumes:
            - /data/dns/pihole/:/etc/pihole/
            - /data/dns/dnsmasq.d/:/etc/dnsmasq.d/
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.labels.dns==true"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.docker.network=server_traefik"
                - "traefik.web.port=80"
                - "traefik.web.frontend.rule=Host:dns.${HOST}"

    doh-proxy:
        image: ngalayko/doh-proxy:arm32v7
        command:
            - "--upstream-resolver=pihole"
            - "--port=3000"
            - "--listen-address=0.0.0.0"
            - "--trusted"
        networks:
            - traefik
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.docker.network=server_traefik"
                - "traefik.dns.port=3000"
                - "traefik.dns.frontend.rule=Host:connect.dns.${HOST}"
