version: '3.3'

configs:
    traefik.toml:
        file: ../../containers/proxy/conf/traefik.toml

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        configs:
            - source: traefik.toml
              target: /etc/traefik/traefik.toml
        ports:
            - 80:80
            - 443:443
        environment:
            - DO_AUTH_TOKEN=${DIGITAL_OCEAN_AUTH_TOKEN}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure

networks:
    traefik:
        driver: overlay
