version: '3'

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        container_name: proxy
        command: --api --docker
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
