version: '3.3'

services:
     blog:
        image: ngalayko/blog:arm32v7
        networks:
            - traefik
        deploy:
            replicas: 3
            labels:
                - "traefik.port=80"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:blog.test.galayko.rocks"
