version: '3.4'

networks:
    fathom:
        driver: overlay

services:
    fathom:
        image: ngalayko/fathom:arm32v7
        networks:
            - traefik
            - fathom
        environment:
            - FATHOM_DEBUG=false
            - FATHOM_DATABASE_DRIVER=postgres
            - FATHOM_DATABASE_URL=postgres://postgres:${POSTGRES_PASS}@postgres/fathom?sslmode=disable
            - FATHOM_SECRET=${FATHOM_SECRET}
        deploy:
            replicas: 1
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:analytics.${HOST}"

    goaccess:
        image: ngalayko/goaccess:arm32v7
        volumes:
            - /data/stats:/srv
            - /data/stats/log:/srv/log
            - /data/stats/certs:/srv/data/certs
        networks:
            - traefik
        ports:
            - 8443:443
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
                    - "node.labels.blog==true"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=443"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:ws.stats.${HOST}"

    goaccess-front:
        image: ngalayko/nginx:arm32v7
        volumes:
            - /data/stats/report:/usr/share/nginx/html:ro
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role==manager"
                    - "node.labels.blog==true"
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=80"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:stats.${HOST}"
