version: '3.4'

networks:
    rss:
        driver: overlay

services:
    miniflux:
        image: miniflux/miniflux:arm32v6-2.0.13
        networks:
            - rss
            - traefik
            - default
        environment:
            - PORT=8080
            - BASE_URL=https://rss.${HOST}
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=ngalayko
            - ADMIN_PASSWORD=${RSS_PASSWORD}
            - POLLING_FREQUENCY=5
            - DATABASE_URL=postgres://postgres:${POSTGRES_PASS}@postgres/miniflux2?sslmode=disable
        deploy:
            replicas: 1
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:rss.${HOST}"
            restart_policy:
                condition: on-failure
