version: '3.4'

networks:
    outside:
        external:
            name: "host"

services:
    wifi-ap-supervisor:
        image: arm32v6/docker
        command: docker run -it \
            -e INTERFACE=wlan0 \
            -e SSID=${WIFI_SSID} \
            -e WPA_PASSPHRASE=${WIFI_PASSWORD} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --privileged \
            ngalayko/docker-ap:arm32v7
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
