version: '3.4'

networks:
    traefik:
        driver: overlay

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        ports:
            - 80:80
            - 443:443
            - 8090:8080
        environment:
            - DO_AUTH_TOKEN=${DIGITAL_OCEAN_AUTH_TOKEN}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
        networks:
            - traefik
            - monitoring
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure
