version: '3.3'

networks:
    traefik:
        driver: overlay

volumes:
    traefik_acme_certificates:

configs:
    traefik_config:
        file: ../../containers/traefik/conf/traefik.toml

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        configs:
            - source: traefik_config
              target: /etc/traefik/traefik.toml
        ports:
            - 80:80
            - 443:443
        environment:
            - DO_AUTH_TOKEN=${DIGITAL_OCEAN_AUTH_TOKEN}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - traefik_acme_certificates:/etc/traefik/acme/acme.json
        networks:
            - traefik
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure
