version: '3.4'

networks:
    home_assistant_host:
        external:
             name: "host"

volumes:
    home_assistant_config:

services:
    home-assistant:
        image: ngalayko/home-assistant:arm32v7
        networks:
            - home_assistant_host
        environment:
            - LONGITUDE=${LONGITUDE}
            - LATITUDE=${LATITUDE}
            - HOST=home.{HOST}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DARKSKY_TOKEN=${DARKSKY_TOKEN}
            - POSTGRES_PASS=${POSTGRES_PASS}
        volumes:
            - home_assistant_config:/config/.storage
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.port=8123"
                - "traefik.docker.network=host"
                - "traefik.frontend.rule=Host:home.${HOST}"
            placement:
                constraints:
                    - "node.labels.home==true"
