version: '3.3'

volumes:
    matomo_data:

networks:
    analytics:
        driver: overlay

services:
    analytics-data:
        image: ngalayko/mysql:arm32v7
        networks:
            - analytics
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - matomo_data:/var/lib/mysql/
            - ../../containers/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    analytics-backend:
        image: ngalayko/matomo:arm32v7
        networks:
            - analytics
        depends_on:
            - analytics-data
        volumes:
            - matomo_data:/var/www/html

    analytics-frontend:
        image: ngalayko/nginx:arm32v7
        networks:
            - traefik
            - analytics
        volumes:
            - matomo_data:/var/www/html
            - ../../containers/analytics/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - analytics-backend
        deploy:
            replicas: 1
            labels:
                - "traefik.port=80"
                - "traefik.docker.network=server_traefik"
                - "traefik.frontend.rule=Host:analytics.${HOST}"
