version: '3'

services:
    proxy:
        image: ngalayko/proxy:arm32v7
        command: 
            - --api.dashboard
            - --docker 
            - --docker.swarmmode 
            - --docker.watch 
            - --docker.domain=docker.swarm
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
        networks:
            - traefik
        deploy:
            replicas: 1
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=traefik"
                - "traefik.frontend.rule=Host:admin.docker.swarm"
            placement:
                constraints: 
                    - "node.role==manager"
            restart_policy:
                condition: on-failure

    visualizer:
        image: alexellis2/visualizer-arm:latest
        networks:
            - traefik
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=traefik"
                - "traefik.frontend.rule=Host:swarm.docker.swarm"
            placement:
                constraints: 
                    - "node.role==manager"

networks:
    traefik:
        driver: overlay
