version: '3.4'

volumes:
    test_volume:
        driver: "ngalayko/sshfs:arm32v7"
        driver_opts:
            sshcmd: "pirate@node-white:/home/pirate/data/test" 
            allow_other: ""

services:
    test:
        image: arm32v7/busybox
        command: "sh"
        volumes:
            - test_volume:/mounted
        deploy:
            replicas: 1
