apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: default-server-secret
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  secretName: default-server-secret
  dnsNames:
  - galaiko.rocks
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
