apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress 
  labels:
    app: nginx-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
