apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: nginx-ingress

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-openvpn-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  type: LoadBalancer
  ports:
    - name: openvpn
      port: 1194
      nodePort: 31294
      targetPort: openvpn
      protocol: UDP
  selector:
    app: nginx-ingress
