apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tcp
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 31360
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      nodePort: 31259
      targetPort: 443
      protocol: TCP
  selector:
    app: nginx-ingress
