kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  selector:
    app: nginx-ingress
  ports:
    - name: http
      port: 80
      nodePort: 31292
      targetPort: http
    - name: https
      port: 443
      nodePort: 31293
      targetPort: https
  type: LoadBalancer
