apiVersion: v1
kind: Service
metadata:
  name: "consul"
  namespace: "consul"
  labels:
    component: "consul-consul"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    port: 8500
  - name: rpc
    port: 8400
  - name: serflan-tcp
    protocol: "TCP"
    port: 8301
  - name: serflan-udp
    protocol: "UDP"
    port: 8301
  - name: serfwan-tcp
    protocol: "TCP"
    port: 8302
  - name: serfwan-udp
    protocol: "UDP"
    port: 8302
  - name: server
    port: 8300
  - name: consuldns-tcp
    port: 8600
  - name: consuldns-udp
    protocol: "UDP"
    port: 8600
  clusterIP: None
  selector:
    component: "consul-consul"

---
apiVersion: v1
kind: Service
metadata:
  name: "consul-ui"
  namespace: "consul"
  labels:
    component: "consul-consul"
spec:
  ports:
  - name: http
    port: 8500
  selector:
    component: "consul-consul"
  type: "NodePort"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul-ui
  namespace: consul
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Consul'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - consul.galaiko.rocks
    secretName: consul-tls
  rules:
  - host: consul.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: consul-ui
          servicePort: http
