version: '3'

services:
    autoheal:
        image: ngalayko/autoheal
        container_name: autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - AUTOHEAL_INTERVAL = 10
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
