apiVersion: v1
kind: Namespace
metadata:
  name: remark

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: remark
  namespace: remark
  labels:
    app: remark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remark
  template:
    metadata:
      namespace: remark
      annotations:
        backup.velero.io/backup-volumes: "remark-data"
      labels:
        app: remark
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: remark
        image: ngalayko/remark
        imagePullPolicy: Always
        args:
        - server
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
          - mountPath: /srv/var
            name: remark-data
            readOnly: false
          - mountPath: /tls
            name: tls-certificate
            readOnly: true
        env:
        - name: SSL_PORT
          value: "8443"
        - name: SSL_CERT
          value: "/tls/tls.crt"
        - name: SSL_KEY
          value: "/tls/tls.key"
        - name: EMOJI
          value: "true"
        - name: SSL_TYPE
          value: "static"
        - name: REMARK_PORT
          value: "8080"
        - name: REMARK_URL
          value: https://remark.galaiko.rocks
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: remark-secret
              key: REMARK_SECRET
        - name: ADMIN_EMAIL
          value: nikita+remark@galaiko.rocks
        - name: ADMIN
          value: github_8eb2bf7120d8b97c88c96bdd6d37cd74b015f2a0
        - name: AUTH_GITHUB_CID
          valueFrom:
            secretKeyRef:
              name: github-cid
              key: GITHUB_CID
        - name: AUTH_GITHUB_CSEC
          valueFrom:
            secretKeyRef:
              name: github-csec
              key: GITHUB_CSEC
        - name: AUTH_GOOGLE_CID
          valueFrom:
            secretKeyRef:
              name: google-cid
              key: GOOGLE_CID
        - name: AUTH_GOOGLE_CSEC
          valueFrom:
            secretKeyRef:
              name: google-csec
              key: GOOGLE_CSEC
        - name: SITE
          value: nikitag-remark
        - name: USER
          value: "0"

      volumes:
      - name: remark-data
        persistentVolumeClaim:
          claimName: remark-data
      - name: tls-certificate
        secret:
          secretName: tls-certificate
