apiVersion: v1
kind: Service
metadata:
  name: remark
  labels:
    app: remark
spec:
  selector:
    app: remark
  ports:
    - name: http
      port: 8080
      targetPort: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remark
  labels:
    app: remark
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - remark.galaiko.rocks
    secretName: remark-tls
  rules:
  - host: remark.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: remark
          servicePort: http
