apiVersion: v1
kind: Service
metadata:
  name: remark
  namespace: remark
  labels:
    app: remark
spec:
  selector:
    app: remark
  ports:
    - name: https
      port: 8443
      targetPort: https

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remark
  namespace: remark
  labels:
    app: remark
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - remark.galaiko.rocks
    secretName: remark-tls
  rules:
  - host: remark.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: remark
          servicePort: https
