kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: remark-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: remark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
