// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VirtualServerListerExpansion allows custom methods to be added to
// VirtualServerLister.
type VirtualServerListerExpansion interface{}

// VirtualServerNamespaceListerExpansion allows custom methods to be added to
// VirtualServerNamespaceLister.
type VirtualServerNamespaceListerExpansion interface{}

// VirtualServerRouteListerExpansion allows custom methods to be added to
// VirtualServerRouteLister.
type VirtualServerRouteListerExpansion interface{}

// VirtualServerRouteNamespaceListerExpansion allows custom methods to be added to
// VirtualServerRouteNamespaceLister.
type VirtualServerRouteNamespaceListerExpansion interface{}
