- id: '1546192302395'
  alias: Alarm
  trigger:
  - at: 05:45:00
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.nikitas_iphone
    state: home
  action:
  - alias: ''
    data:
      entity_id: scene.morning
    service: scene.turn_on
- id: '1546193382011'
  alias: Turn off lights
  trigger:
  - entity_id: device_tracker.nikitas_iphone
    platform: state
    from: home
    to: not_home
  action:
  - data:
      entity_id: scene.night
    service: scene.turn_on
- id: '1546193382012'
  alias: Welcome
  trigger:
  - entity_id: device_tracker.nikitas_iphone
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: scene.evening
    service: scene.turn_on
