homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: ${LONGITUDE}
  longitude: ${LATITUDE}
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Database setup
recorder:
    db_url: postgresql://postgres:${POSTGRES_PASS}@postgres/home_assistant?sslmode=disable

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables discovery.
discovery:
    enable:
        - homekit

http:
   base_url: ${HOST}

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Weather
weather:
  - platform: darksky
    api_key: ${DARKSKY_TOKEN}
    name: Dark Sky

# Telegram
telegram_bot:
  - platform: polling
    api_key: ${TELEGRAM_TOKEN}
    allowed_chat_ids:
      - 109935692

# Notifications
notify:
  - name: Home Assistant
    platform: telegram
    chat_id: 109935692

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
