homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: ${LONGITUDE}
  longitude: ${LATITUDE}
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enabled homekit integration
homekit:

ios:

# Use Apple TV as a media player.
apple_tv:
    - host: ${APPLE_TV_IP}
      name: Living Room Apple TV
      login_id: ${APPLE_TV_ID}
      start_off: true
      credentials: ${APPLE_TV_SECRET}

# Enables discovery.
discovery:
    ignore:
        - google_cast
        - plex_mediaserver
        - samsung_tv
    enable:
        - homekit

http:
   base_url: ${HOST}
   api_password: ${HOME_ASSISTANT_PASSWORD}

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather
weather:
  - platform: darksky
    api_key: ${DARKSKY_TOKEN}
    name: Dark Sky

# Telegram
telegram_bot:
  - platform: polling
    api_key: ${TELEGRAM_TOKEN}
    allowed_chat_ids:
      - 109935692

# Notifications
notify:
  - name: Home Assistant
    platform: telegram
    chat_id: 109935692

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
device_tracker: !include trackers.yaml
sensor: !include sensors.yaml
