living_room:
    name: Living room
    entities:
        - sensor.living_room__switch
        - light.living_room__ceiling_lamp__1
        - light.living_room__ceiling_lamp__2
        - light.living_room__corner_lamp
        - media_player.living_room

kitchen:
    name: Kitchen
    entities:
        - sensor.kitchen__switch 
        - light.kitchen__ceiling_led__1
        - light.kitchen__ceiling_led__2
        - light.kitchen__ceiling_led__3

entrance:
    name: Entrance
    entities:
        - sensor.entrance__switch
        - light.entrance__ceiling_led__1
        - light.entrance__ceiling_led__2
        - light.entrance__ceiling_led__3


bathroom:
    name: Bathroom
    entities:
        - sensor.bathroom__motion_sensor
        - light.bathroom__ceiling_led__1
        - light.bathroom__ceiling_led__2

bedroom:
    name: Bedroom
    entities:
        - sensor.bedroom__switch 
        - light.bedroom__ceiling_lamp__1
        - light.bedroom__ceiling_lamp__2
