nikitasapple_watch:
  hide_if_away: false
  icon:
  mac:
  name: Nikita’s Apple Watch
  picture:
  track: false

nikitasiphone:
  hide_if_away: false
  icon:
  mac: ${IPHONE_MAC}
  name: Nikita
  gravatar: ngalayko@gmail.com
  track: true
