- name: Home
  latitude: ${HOME_LATITUDE}
  longitude: ${HOME_LONGTITUDE}
  radius: 250
  icon: mdi:home

- name: WORK
  latitude: ${WORK_LATITUDE}
  longitude: ${WORK_LONGTITUDE}
  radius: 250
  icon: mdi:briefcase
