apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: nikita+letsencrypt@galaiko.rocks
   privateKeySecretRef:
     name: letsencrypt
   solvers:
   - dns01:
       cloudflare:
         email: nikita+cloudflare@galaiko.rocks
         apiKeySecretRef:
           name: cloudflare-api-key-secret
           key: CLOUDFLARE_TOKEN
