defaultEntryPoints = ["http", "https"]

[api]
  dashboard=true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    compress = true
      [entryPoints.https.tls]

[acme]
  email = "ngalayko@gmail.com"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  OnHostRule = true
  acmeLogging = true

[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[docker]
  domain = "galayko.rocks"
  watch = true
  swarmmode = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]
