apiVersion: batch/v1
kind: Job
metadata:
  name: dnscrypt-init
spec:
  template:
    metadata:
      name: dnscrypt-init
    spec:
      containers:
      - name: dnscrypt-init
        image: jedisct1/unbound-dnscrypt-server
        command: ["/entrypoint.sh", "init",  "-N", "example.com", "-E", "192.168.1.1:443"]
        volumeMounts:
          - name: dnscrypt-keys
            mountPath: /opt/dnscrypt-wrapper/etc/keys
      restartPolicy: Never
      volumes:
        - name: dnscrypt-keys
          gcePersistentDisk:
            pdName: dnscrypt-keys
            fsType: ext4
