apiVersion: v1
kind: Namespace
metadata:
  name: doh-proxy

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: doh-proxy
  namespace: doh-proxy
  labels:
    app: doh-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doh-proxy
  template:
    metadata:
      namespace: doh-proxy
      labels:
        app: doh-proxy
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: doh-proxy
        image: ngalayko/doh-proxy
        args:
        - --upstream-resolver=pihole-dns.pihole
        - --port=3000
        - --listen-address=0.0.0.0
        - --trusted
        ports:
        - containerPort: 3000
          name: http
