apiVersion: v1
kind: Service
metadata:
  name: doh-proxy
spec:
  selector:
    app: doh-proxy
  ports:
    - name: http
      port: 3000
      targetPort: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doh-proxy
spec:
  rules:
  - host: connect.dns.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: doh-proxy
          servicePort: http
