FROM arm32v7/debian:7.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl

RUN curl --silent --show-error --fail --location \
	--header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o /usr/bin/minio \
	"https://dl.minio.io/server/minio/release/linux-arm/minio" \
	 && chmod 0755 /usr/bin/minio

EXPOSE 9000
VOLUME ["/export"]
ENTRYPOINT ["./docker-entrypoint.sh"]
