apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: arm32v7/postgres:11.5
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 128Mi
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
            readOnly: false
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pass
                key: POSTGRES_PASS
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
