apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
data:
  grafana.ini: |
    [analytics]
    reporting_enabled = false
    check_for_updates = true
    [dashboards]
    versions_to_keep = 5
    [metrics]
    enabled = false
    [snapshots]
    external_enabled = false
    [alerting]
    enabled = false
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
