apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: default
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31289
      name: http
    - protocol: TCP
      port: 443
      nodePort: 31290
      name: https
  type: NodePort
