apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: velero
  labels:
    app: velero
spec:
  schedule: "0 0 * * *"
  template:
    snapshotVolumes: true
    includedResources:
    - "*"
    includedNamespaces:
    - "*"
    ttl: 72h
