apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
  labels:
    app: velero
spec:
  provider: aws
  objectStorage:
    bucket: cluster.backup
  config:
    region: eu-north-1
