apiVersion: v1
kind: ConfigMap
metadata:
  name: "vault-config"
  namespace: vault
  labels:
    app: "vault"
data:
  config.json: |
    {
        "ui": true,
        "listener":{
            "tcp":{
                "address": "[::]:8200",
                "cluster_address": "[::]:8201",
                "tls_disable": false,
                "tls_cert_file": "/tls/tls.crt",
                "tls_key_file": "/tls/tls.key",
                "tls_client_ca_file": "/tls/ca.crt"
            }
        },
        "storage": {
            "consul": {
                "address": "consul.consul:8500"
            }
        }
    }

