apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  type: ClusterIP
  ports:
  - port: 8200
    name: api
  selector:
    app: vault

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-ui
  namespace: vault
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - vlt.galaiko.rocks
    secretName: vault-tls
  rules:
  - host: vlt.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: vault
          servicePort: api
