kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  ports:
    - name: tcp
      port: 8443
      targetPort: tcp
      protocol: TCP
  selector:
    app: openvpn

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openvpn
spec:
  rules:
  - host: vpn.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: openvpn
          servicePort: tcp
