kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  ports:
    - name: openvpn-udp
      port: 1194
      targetPort: openvpn-udp
      protocol: UDP
  selector:
    app: openvpn

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    stream-snippets: |
      upstream openvpn-udp {
          server connect.dns.galaiko.rocks:1194;
      }
      server {
          listen 1194 udp;
          proxy_pass openvpn-udp;
          proxy_responses 1;
      }
