kind: Service
apiVersion: v1
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
spec:
  ports:
  - name: udp
    port: 1194
    targetPort: udp
    protocol: UDP
  selector:
    app: openvpn
