kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  ports:
    - name: tcp
      port: 1194
      targetPort: tcp
      protocol: TCP
  selector:
    app: openvpn

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openvpn
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - connect.vpn.galaiko.rocks
    secretName: openvpn-tls
  rules:
  - host: connect.vpn.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: openvpn
          servicePort: tcp
