kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  ports:
    - name: openvpn
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: openvpn
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openvpn
spec:
  rules:
  - host: vpn.galaiko.rocks
    http:
      paths:
      - path: /
        backend:
          serviceName: openvpn
          servicePort: vpn
