kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvpn
  namespace: openvpn
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: openvpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2M
