language: bash

services: 
    - docker

script:
    - docker build -t blog .
    - docker run --rm -it -v /blog:/export blog sh -c 'cp -r /app/public/* /export'

after_success:
- find /blog -type f -exec curl
    -T {}
    --ftp-create-dirs
    --user ${SFTP_USER}:${SFTP_PASSWORD}
    "ftp://ftp.fastmail.com/nikita.galaiko.rocks/files/{}" ';'
