name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
        - cert-manager
        - doh-proxy
        - fathom
        - kube-dashboard
        - miniboard
        - miniflux
        - nfs-client
        - nginx-ingress
        - openvpn
        - pihole
        - postgres
        - redis
        - remark
        - weave
    
    steps:
    - uses: actions/checkout@v1

    - name: Apply charts
      uses: exelban/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f /github/workspace/k8s/${{ matrix.chart }}
