version: "3"
services:
  fathom:
    image: usefathom/fathom:latest
    ports:
      - "8080:8080"
    environment:
      - "FATHOM_SERVER_ADDR=:8080"
      - "FATHOM_GZIP=true"
      - "FATHOM_DEBUG=false"
      - "FATHOM_DATABASE_DRIVER=mysql"
      - "FATHOM_DATABASE_NAME=fathom"
      - "FATHOM_DATABASE_USER=fathom"
      - "FATHOM_DATABASE_PASSWORD=password01"
      - "FATHOM_DATABASE_HOST=mysql:3306"
      - "FATHOM_SECRET=TWEn6GXQDx45PZfmJWvyGpXf5M8b94bszgw8JcJWEd6WxgrnUkLatS34GwjPTvZb"
    links:
      - "mysql:mysql"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: "mysql:5"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
      - "MYSQL_DATABASE=fathom"
      - "MYSQL_PASSWORD=password01"
      - "MYSQL_ROOT_PASSWORD=password01"
      - "MYSQL_USER=fathom"
    restart: always
